services:
  - type: web
    name: brydge-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ENABLE_DB
        value: true
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        fromGroup: brydge-secrets
      - key: MONGODB_URI
        fromGroup: brydge-secrets
